[package]
name = "torrent-client"
version = "0.1.0"
edition = "2021"

[dependencies]
vdk-bencode = {path = "../vdk-bencode"}
url = "2.5.2"
thiserror = "1.0"
clap = {version = "4.5.8", features = ["derive"]}