[package]
name = "torrent"
version = "0.1.0"
authors = ["VxDxK"]
edition = "2024"
repository = "https://github.com/VxDxK/vdk-torrent-client"
keywords = ["torrent", "torrent-client"]
categories = ["network-programming"]

[dependencies]
bencode = {path = "../bencode" }
url = "2.5"
percent-encoding = "2.3"
thiserror = "2"
sha1 = "0.10"
reqwest = { version = "0.12", features = ["blocking"] }
rand = "0.9"
bytes = "1"